export let products = [
  {
    title: "Reloj Batman",
    img: "https://res.cloudinary.com/dphzc4d5r/image/upload/v1696376668/3_ttppjx.jpg",
    descripcion: "Reloj Batman calado artesanal, detalles cuidadosamente realizados manualmente",
    stock: 4,
category: "relojes",
    precio: 3000,
  },
  {
    title: "Cuadro tridimensional",
    img: "https://res.cloudinary.com/dphzc4d5r/image/upload/v1696376614/1_x8hkab.jpg",
    descripcion: "Tapizado estrella rojo confeccionado con hilo 100% algodón",
    stock: 3,
category: "decoracion",
    precio: 6000,
  },
  {
    title: "Cuadro 3D en hilo",
    img: "https://res.cloudinary.com/dphzc4d5r/image/upload/v1696376644/8_diuzz5.jpg",
    descripcion: "Tapizado en hilo amarillo confeccionado con hilo 100% algodón",
    stock: 5,
category: "decoracion",
    precio: 6000,
  },
  {
    title: "Funda Deco",
    img: "https://res.cloudinary.com/dphzc4d5r/image/upload/v1696376547/hiloalmohadon_ackmxm.png",
    descripcion: "Funda macramé para almohadón confeccionado artesanalmente con hilo 100% algodón",
    stock: 5,
category: "decoracion",
    precio: 4000,
  },
  {
    title: "Tapiz macramé",
    img: "https://res.cloudinary.com/dphzc4d5r/image/upload/v1696376589/decotrenzado_midp3a.jpg",
    descripcion: "Tapiz decotativo macramé hojas confeccionado con hilo 100% algodón teñido",
    stock: 8,
category: "decoracion",
    precio: 7000,
  },
  {
    title: "Reloj elefante",
    img: "https://res.cloudinary.com/dphzc4d5r/image/upload/v1696376565/elefante_reloj_lt0isl.jpg",
    descripcion: "Reloj elefante en vinilo, detalles cuidadosamente realizados manualmente",
    stock: 30,
category: "relojes",
    precio: 3000,
  },
  {
    title: "Reloj caballo",
    img: "https://res.cloudinary.com/dphzc4d5r/image/upload/v1696376523/relojcaballo_e2fe3f.png",
    descripcion: "Relojes de pared caballo con vinilos calados, detalles cuidadosamente realizados manualmente",
    stock: 6,
category: "relojes",
    precio: 2500,
  },
  {
    title: "Reloj león",
    img: "https://res.cloudinary.com/dphzc4d5r/image/upload/v1696376469/1680391995419_czrecm.jpg",
    descripcion: "Reloj de pared león, personalizados según preferencias",
    stock: 10,
category: "relojes",
    precio: 3000,
  },
  {
    title: "Cuandro tridimensional",
    img: "https://res.cloudinary.com/dphzc4d5r/image/upload/v1696376442/cuadrohilo_zvbrgq.png",
    descripcion: "Cuadro tridimencional con hilo confeccionado artesanalmente con hilo 100% algodón",
    stock: 8,
    category: "decoracion",
    precio: 6000,
  },
];
